-- Encontrar produtos com o preço entre 50 e 150
SELECT *
FROM produto
WHERE produto.preco >=50 AND produto.preco <=150;

SELECT * FROM produto
WHERE preco BETWEEN 50 AND 150;

-- MOSTRE TUDO DOS PRODUTOS COM ID 1, 5 e 7

SELECT *
FROM produto
WHERE id = 1 OR id = 5 OR id=7;

SELECT * FROM produto
WHERE id IN (1,3,7);

-- MOSTRE TODOS OS CLIENTES QUE O SOBRENOME TERMINE COM 'A'

SELECT *
FROM cliente
 WHERE sobrenome LIKE '%a';
 
 -- MOSTRE OS 5 PRODUTOS MAIS CAROS DA LOJA
SELECT *
FROM PRODUTO
ORDER BY preco DESC
LIMIT 5;

-- LISTADO OS PRODUTOS POR PÁGINA, CADA PÁGINA CABENDO 2 PRODUTOS, ME MOSTRE A PÁGINA 3

SELECT * FROM produto
LIMIT 2 OFFSET 4;

-- CONSULTAR OS PEDIDOS FEITOS ENTRE 2024-03-01 E 2024-03-02-01, LIMITANDO A 5 RESULTADOS
SELECT * 
FROM PEDIDO
WHERE dataPedido BETWEEN '2024-03-01' AND '2024-03-05'
ORDER BY dataPedido
LIMIT 5;